### PR TITLE
Fix Client::dispatch_until() timing out early

### PR DESCRIPTION
**Pull request by RAOF**
Because `duration_cast<milliseconds>(maximum_wait)` performs integer division we lose any fractional milliseconds in `maximum_wait`, meaning that `poll()` could return up to 1ms before we were intending to timeout.

### CODE REVIEW

**Comment by RAOF** [comment]
Bors try

**Comment by RAOF** [comment]
Bors try

Let's give it a second chance at failing

**Comment by RAOF** [comment]
That was a Fedora setup issue...

bors try

**Comment by AlanGriffiths** [comment]
That was a Fedora setup issue...

bors try

**Comment by RAOF** [comment]
Ok. I'm *reasonably* certain that this now *actually* fixes the problem.

**Comment by AlanGriffiths** [comment]
LGTM

bors r+

**Pull request merged**
