### PR TITLE
[debian] use 1.0 source format

### PR DESCRIPTION
**Pull request by Saviq**
Our CI is not equipped for 3.0 just yet.

### CODE REVIEW

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
bors r=RAOF,AlanGriffiths

**Comment by AlanGriffiths** [comment]
bors r=RAOF,AlanGriffiths

**Comment by AlanGriffiths** [comment]
bors r=RAOF,AlanGriffiths

**Pull request merged**
