### PR TITLE
Release WLCS 1.2

### PR DESCRIPTION
**Pull request by RAOF**

### CODE REVIEW

**Comment by RAOF** [comment]
Ok. WLCS itself appears to be good to go, but
1. Mir fails a bunch of tests now - thanks to the fixed interpretation of the `wl_subsurface` interface, and the additional tests for touch-up and keyboard-leave on surface destroy
2. WLCS fails to build on groovy, due to [a libwayland-dev bug](https://bugs.launchpad.net/ubuntu/+source/wayland/+bug/1893738)

We should probably wait until (2) is resolved before releasing.

**Comment by wmww** [comment]
Heads up, most of our Layer Shell tests are making protocol violations that are fixed in #181. Mir will start sending errors for those violations after https://github.com/MirServer/mir/pull/1720, so we might want to get #181 into a release if possible.

**Comment by RAOF** [comment]
That sounds worth delaying the 1.2 release for!

**Review by wmww — APPROVED** [review]
LGTM

**Comment by RAOF** [comment]
bors cancel

**Comment by RAOF** [comment]
bors r=wmww

**Pull request merged**
