### PR TITLE
ci: refresh Ubuntu

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by wmww — APPROVED** [review]
bors r+

**Comment by Saviq** [comment]
Yeah this needs to wait for LXD images of 22.10 :]

**Comment by Saviq** [comment]
NB: this targets [use-spread-mir-ci](https://github.com/MirServer/wlcs/tree/use-spread-mir-ci)

**Review by RAOF — APPROVED** [review]
This is still correct, and now the prerequisite branch has landed. Thanks, bors, for retargetting automatically!

bors r+

**Pull request merged**
