### PR TITLE
[gha] migrate from Travis

### PR DESCRIPTION
**Pull request by Saviq**
---

This simulates a `master` push: https://github.com/MirServer/wlcs/actions/runs/408205675

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
Can't make things worse. I have to trust that errors will be visible.

bors r+

**Comment by Saviq** [comment]
Forgot to tell bors to respect these…

bors r-

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
Grrh.

bors r=AlanGriffiths

**Pull request merged**
