### PR TITLE
WLCS 1.1.0 release

### PR DESCRIPTION
**Pull request by RAOF**
* Document the compositor-integration version macros
 * Add tests for the `wl_output` protocol
 * More tests for XDG Shell, particularly around popups and window movement
 * Add tests for `wp_primary_selection_unstable_v1 protocol`
 * Add tests for `gdk_primary_selection protocol`
 * Lots of build fixes for !Ubuntu systems. Thanks, Neal Gompa!
 * Many cases where WLCS would hang indefinitely will now time-out and mark the test as failed.

### CODE REVIEW

**Comment by wmww** [comment]
Talked to @AlanGriffiths, and we agreed we don't need to hold up the release for layer surface tests to land.

**Comment by RAOF** [comment]
bors r=AlanGriffiths

**Comment by RAOF** [comment]
Hm. Real time, my only weakness!

Failing twice in a row seems like time to loosen the expectations :/

**Comment by AlanGriffiths** [comment]
LGTM

> bors r=AlanGriffiths

I don't think we want to land just yet: the release package isn't in the PPA.

It looks like there's a v1.1.0 tag, so I'm not sure what's not joined up...

**Comment by Conan-Kudo** [comment]
> Lots of build fixes for !Ubuntu systems. Thanks, Neal Gompa!

Aww, you're welcome! I'm happy to help wherever I can! 😊

**Comment by RAOF** [comment]
Ok. It looks like the release package is in the rc PPA, leaving the final step being to copy it to the release PPA. By my understanding that happens when the v1.1.0 tag appears on master, so once this has merged…

bors r=AlanGriffiths

**Comment by RAOF** [comment]
Damn it, Fedora!

Bors r=AlanGriffiths

**Comment by RAOF** [comment]
bors r=AlanGriffiths

**Comment by AlanGriffiths** [comment]
I'll merge this...

**Pull request merged**
