### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
> Run tools/ppa-upload.sh
> Setting version to:
>   1.2.1+dev69-g8742e22-0ubuntu20.04

That looks wrong too. Hmm!

**Comment by AlanGriffiths** [comment]
> Hm. That looks like the test might be wrong (`int` vs `wl_fixed` confusion?)

It does look like `int` vs `wl_fixed` confusion, but is it the test that's wrong?

`Pointer::move_to()` takes `int`s that are internally converted to `wl_fixed` (and on the Mir side, in `wlcs_pointer_move_absolute(()` these are converted from `wl_fixed` to `double`.

Similarly, `Client::pointer_position()` is returning `wl_fixed_t` (which is set from `wl_fixed_t` values received from the server).

It looks as though the problem is on the Mir side (probably in the event faking for the wlcs plugin).

**Comment by wmww** [comment]
I believe your assessment is incorrect. Using `wl_fixed` is obfuscating the error (we should probably change it for that reason), but is not the source of the problem.

The root cause is https://github.com/MirServer/mir/issues/1792. If `touch.move_to(0, 0);` on line 258 is commented out the test passes, because Mir no longer has an alternative input event to get confused by. Fixing that is one of the many back-burner projects I have that isn't related to any roadmap items.

**Comment by AlanGriffiths** [comment]
I see some puzzling errors: If I switch to the wlcs from ppa:mir-team/wlcs-rc (instead of ppa:mir-team/dev) then I see a lot of tests failing that I don't expect (as they shouldn't have changed) e.g.

```plain
$ $(pkg-config --variable test_runner wlcs) cmake-build-debug/lib/miral_wlcs_integration.so --gtest_filter=CopyCutPaste.*
Note: Google Test filter = CopyCutPaste.*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from CopyCutPaste
[ RUN      ] CopyCutPaste.given_source_has_offered_when_sink_gets_focus_it_sees_offer
/build/wlcs-Nlsc0C/wlcs-1.2.0~rc3.git8011b95/tests/copy_cut_paste.cpp:106: Failure
Actual function call count doesn't match EXPECT_CALL(mdol, offer(_, StrEq(any_mime_type)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
/build/wlcs-Nlsc0C/wlcs-1.2.0~rc3.git8011b95/tests/copy_cut_paste.cpp:107: Failure
Actual function call count doesn't match EXPECT_CALL(sink.listener, data_offer(_,_))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] CopyCutPaste.given_source_has_offered_when_sink_gets_focus_it_sees_offer (30 ms)
[ RUN      ] CopyCutPaste.given_sink_has_focus_when_source_makes_offer_sink_sees_offer
/build/wlcs-Nlsc0C/wlcs-1.2.0~rc3.git8011b95/tests/copy_cut_paste.cpp:118: Failure
Actual function call count doesn't match EXPECT_CALL(mdol, offer(_, StrEq(any_mime_type)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
/build/wlcs-Nlsc0C/wlcs-1.2.0~rc3.git8011b95/tests/copy_cut_paste.cpp:119: Failure
Actual function call count doesn't match EXPECT_CALL(sink.listener, data_offer(_,_))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] CopyCutPaste.given_sink_has_focus_when_source_makes_offer_sink_sees_offer (35 ms)
[----------] 2 tests from CopyCutPaste (65 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test cases run. (65ms total elapsed)
[  PASSED  ] 0 tests
[  FAILED  ] 2 tests failed:
[  FAILED  ] CopyCutPaste.given_sink_has_focus_when_source_makes_offer_sink_sees_offer
[  FAILED  ] CopyCutPaste.given_source_has_offered_when_sink_gets_focus_it_sees_offer
```

Switching back to wlcs from ppa:mir-team/dev works as expected.

**Comment by AlanGriffiths** [comment]
> Switching back to wlcs from ppa:mir-team/dev works as expected.

As does using a local build of the release branch. /o\

**Comment by AlanGriffiths** [comment]
> I see some puzzling errors: If I switch to the wlcs from ppa:mir-team/wlcs-rc (instead of ppa:mir-team/dev) then I see a lot of tests failing that I don't expect (as they shouldn't have changed) e.g.

Doh! I'm installing an old version from the PPA as the version is all screwed up.

**Comment by AlanGriffiths** [comment]
OK, so @Saviq did some poking and the right version ended up in `ppa:wlcs-dev`. That works for me, so I think code-wise we are good here.

But something is not right with the release process automation/documentation.

**Comment by AlanGriffiths** [comment]
OK, so the script is still broken after I hacked at it.

@Saviq suggests fixing it after the release. I've copied the (mostly successful) build from `ppa:mir-team/wlcs-dev` to `ppa:mir-team/wlcs-rc`.

Shall we land?

**Review by wmww — APPROVED** [review]
LGTM
bors r+

**Comment by AlanGriffiths** [comment]
Is the Fedora 34 failure a blip?

bors r=@wmww

**Comment by AlanGriffiths** [comment]
bors r=wmww

**Comment by AlanGriffiths** [comment]
Not sure what bors is up to today.

Just gonna merge it!

**Pull request merged**
